spring.application.name=estoque-api

spring.datasource.url=jdbc:postgresql://localhost:5432/controle_estoque

spring.datasource.username=postgres

spring.datasource.password=436719

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
